openapi: 3.0.3
info:
  title: Builder Backend API
  description: API specification for the Builder Backend application
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /signup/:
    post:
      summary: Create a new user account
      description: Register a new user with email, password, name, and preferred language
      operationId: signup
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - confirm_password
                - name
                - Preferred_language
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (must be unique)
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password
                  minLength: 1
                  example: SecurePassword123!
                confirm_password:
                  type: string
                  format: password
                  description: Password confirmation (must match password)
                  minLength: 1
                  example: SecurePassword123!
                name:
                  type: string
                  description: User's full name
                  maxLength: 255
                  example: John Doe
                Preferred_language:
                  type: string
                  description: User's preferred language
                  maxLength: 255
                  example: English
            examples:
              valid_request:
                summary: Valid signup request
                value:
                  email: john.doe@example.com
                  password: SecurePassword123!
                  confirm_password: SecurePassword123!
                  name: John Doe
                  Preferred_language: English
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account created successfully
              examples:
                success:
                  summary: Successful account creation
                  value:
                    message: Account created successfully
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Passwords do not match
              examples:
                password_mismatch:
                  summary: Password mismatch error
                  value:
                    error: Passwords do not match
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred while creating the account

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          description: Unique identifier for the user
          readOnly: true
        name:
          type: string
          maxLength: 255
          description: User's full name
        email:
          type: string
          format: email
          description: User's email address
        Preferred_language:
          type: string
          maxLength: 255
          description: User's preferred language
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          readOnly: true

